name: MEXC Alerts

on:
  schedule:
    - cron: "*/15 * * * *"   # 15 dakikada bir
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Repo indiriliyor
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kütüphaneleri kur
      run: pip install requests

    - name: Scripti çalıştır
      run: python alerts.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}

    - name: Değişiklikleri commit et
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add sent_alerts.json
        git commit -m "update alerts" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
