name: MEXC Alerts

on:
  schedule:
    - cron: "*/15 * * * *"   # 15 dakikada bir çalışsın
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Repo indiriliyor
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kütüphaneleri kur
      run: pip install requests

    - name: Scripti çalıştır
      run: python alerts.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
