name: Binance Alerts

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indiriliyor
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Kütüphaneleri kur
        run: pip install requests

      - name: Debug secrets
        run: |
          echo "DEBUG TOKEN = ${TELEGRAM_TOKEN}"
          echo "DEBUG CHATID = ${CHAT_ID}"
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Scripti çalıştır (UNBUFFERED LOG)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python -u alerts.py
